name: 'App To SimpleLocalize Sync'

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CLI_VERSION: '2.10.0'
  SIMPLELOCALIZE_API_KEY_work: ${{ secrets.SIMPLELOCALIZE_API_KEY_WORK }}
  SIMPLELOCALIZE_API_KEY_personal: ${{ secrets.SIMPLELOCALIZE_API_KEY_PERSONAL }}

jobs:
  translation-management:
    runs-on: ubuntu-latest
    name: Preview and Upload Translations
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preview translation upload
        uses: simplelocalize/github-action-cli@v4
        with:
          api-key: ${{ env.SIMPLELOCALIZE_API_KEY_personal }}
          command: 'upload'
          cli-version: ${{ env.CLI_VERSION }}
          args: '--uploadPath ./src/assets/i18n/{lang}.json --uploadFormat single-language-json --uploadOptions UPDATE_ORDER --uploadTags PR-${{ github.event.number }}-branch-${{ github.head_ref || github.ref_name }} --dryRun'

      - name: Upload translation files
        uses: simplelocalize/github-action-cli@v4
        with:
          api-key: ${{ env.SIMPLELOCALIZE_API_KEY_personal }}
          command: 'upload'
          cli-version: ${{ env.CLI_VERSION }}
          args: '--uploadPath ./src/assets/i18n/{lang}.json --uploadFormat single-language-json --uploadOptions UPDATE_ORDER --uploadTags PR-${{ github.event.number }}-branch-${{ github.head_ref || github.ref_name }}'

      - name: Auto-translate missing translations
        uses: simplelocalize/github-action-cli@v4
        with:
          api-key: ${{ env.SIMPLELOCALIZE_API_KEY_personal }}
          command: 'auto-translate'
          cli-version: ${{ env.CLI_VERSION }}
          args: '--languageKeys de-de,es-es,fr-fr'

      - name: Display upload summary
        run: echo "✅ Translation files have been successfully uploaded to SimpleLocalize and auto-translated"
